# Generated by Django 4.2 on 2023-05-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='css',
            options={'verbose_name': 'Css', 'verbose_name_plural': 'Custom Css'},
        ),
    ]
