# Generated by Django 5.0.2 on 2024-02-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_default_domain_default_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='primary_domaIn',
            field=models.BooleanField(default=False),
        ),
    ]
